Vagrant.configure("2") do |config|
    config.ssh.shell = "bash -l"
    config.ssh.keep_alive = true
    config.ssh.forward_agent = true
    config.ssh.forward_x11 = false
    config.vagrant.host = :detect

    config.vm.define "default", primary: true do |default|
        default.ssh.username = "vagrant"
        default.vm.box = "architrave/Debian-jessie"
        default.vm.hostname = "architrave.local"
        default.vm.usable_port_range = (2200..2250)
        default.vm.network :private_network, ip: "10.250.0.10"

        default.vm.provider :virtualbox do |virtualbox, override|
            virtualbox.memory = 2048
            virtualbox.cpus = 2
            virtualbox.name = "architrave"
        end
        
        default.vm.provision :ansible do |ansible|
            #ansible.raw_arguments = "--ask-vault-pass"
            ansible.raw_arguments = "--vault-password-file=passwords.txt"
            ansible.playbook = "playbook-vagrant.yml"
            ansible.become = true
            ansible.become_user = "root"
            ansible.verbose = ''
            ansible.inventory_path = "inventory"
        end
    end
end
