---
- name: "install packages"
  apt:
    pkg: "{{item}}"
    state: "present"
  with_items:
    - "iptables"

- name: "configure iptables"
  template:
    src: "templates/iptables"
    dest: "/etc/iptables.rules"
    owner: "root"
    group: "root"
    mode: "600"
  notify: 
    - bring up iptables
    - load iptables
