---
- name: Adding new base directory
  file:
    path: "{{ base_path }}
    state: directory
    owner: root
    group: "{{ web_user_group }}"
    recurse: yes
    mode: 0750

- name: Adding web user group
  group:
    name: "{{ web_user_group }}"
    state: present

- name: Adding web user
  user:
    name: "{{ web_user }}"
    password: "{{ web_user_password }}"
    comment: Web user
    state: present
    shell: /bin/bash

- name: "NGINX"
  import_tasks: nginx.yml
  tags:
    - nginx

- name: "PHP"
  import_tasks: php.yml
  tags:
    - php
