---
- name: Create testuser
  user:
    name: "{{ test_user }}"
    password: "{{ test_user_password }}"
    state: present
    shell: /bin/bash

- name: "NGINX"
  import_tasks: nginx.yml
  tags:
    - nginx

- name: "PHP"
  import_tasks: php.yml
  tags:
    - php

