---
fqdn: architrave.local

httpd_docroot: /storage/ArchAssets/public
httpd_force_ssl: true
httpd_ssl_enabled: true
httpd_try_files: $uri $uri/ /index.php?$args
httpd_index: index.html index.htm index.php
httpd_client_max_body_size: 150m
httpd_docroot_protected_files: /storage/clear
httpd_sendfile: 'on'
httpd_restrict_health: true

web_group: www-data
web_user: testuser
web_pass: "{{ vault_web_pass }}"
web_user_path: "/var/www/{{ web_user }}"

# when set to true, simplesamlphp location is added to nginx and SSO Auth Adapter
# gets added to ZfcUser config through local.php.
sso_enabled: false

php_packages:
  - php7.0-mysql
  - php7.0-curl
  - php7.0-intl
  - php7.0-mcrypt
  - php7.0-sqlite3
  - php7.0-imagick
  - php7.0-apcu
  - php7.0-apcu-bc
  - php7.0-xml
  - php7.0-bcmath
  - php7.0-mbstring
  - php7.0-zip
  - php7.0-soap

php_ini_overrides:
  - upload_max_filesize=150M
  - post_max_size=155M
  - date.timezone=Europe/Berlin
  - memory_limit=512M
  - session.cache_limiter=
  - session.use_strict_mode=1
  - session.cookie_httponly=1
  - session.cookie_secure=1

php_fpm_ini_overrides:
  - display_errors=Off
  - error_reporting=E_ALL

session_gc_maxlifetime: 1440

# var for setting deferant read timeout other then the nginx default of 30
var_fastcgi_read_timeout: 180

# var for setting php fpm timeout other then the nginx default of 30
max_execution_time:

php_cli_ini_overrides:
  - display_errors=On
  - error_reporting=E_ALL

httpd_ssl_cert_path: /etc/ssl/certs/architrave.crt
httpd_ssl_key_path: /etc/ssl/private/architrave.key

httpd_ssl_cert: "{{ vault_httpd_ssl_cert }}"

httpd_ssl_key: "{{ vault_httpd_ssl_key }}"
