---
# Debian's session cleanup cron only adheres to
# /etc/php/7.0/fpm/php.ini settings, so we need to use that for the session timeout
#- name: "Configure php7.0-fpm session timeout"
#  replace:
#    dest: /etc/php/7.0/fpm/php.ini
#    regexp: '^\s*session.gc_maxlifetime\s*=\s*\d*$'
#    replace: 'session.gc_maxlifetime = {{ session_gc_maxlifetime }}'
#    backup: "yes"
#
#- name: "Configure php-fpm max execution time"
#  replace:
#    dest: /etc/php/7.0/fpm/php.ini
#    regexp: '^\s*max_execution_time\s*=\s*\d*\s*$'
#    replace: 'max_execution_time = {{ max_execution_time }}'
#    backup: "yes"
#  when: max_execution_time is defined and not (max_execution_time is none)

- name: "Configure php.ini overrides for fpm"
  template:
    src: php-fpm.j2
    dest: /usr/local/etc/php/conf.d/architrave-fpm.ini
    owner: root
    group: root
    mode: 0644

- name: "Configure php.ini overrides for cli"
  template:
    src: php-cli.j2
    dest: /usr/local/etc/php/conf.d/architrave-cli.ini
    owner: root
    group: root
    mode: 0644

- name: "Enable status page"
  lineinfile:
    path: /usr/local/etc/php-fpm.d/www.conf
    regexp: "^;pm.status_path"
    line: pm.status_path = /status

- name: "Copy index.php"
  template:
    src: index.php.j2
    dest: /var/www/index.php
    owner: root
    group: root
    mode: 0644
