---
- name: Install php package
  apk: 
    name: "{{ item }}"
    state: present
  with_items: "{{ php_packages }}"

# https://github.com/docker-library/php/issues/279
# https://www.cyberciti.biz/faq/how-to-install-php-7-fpm-on-alpine-linux/
- name: Install PHP extensions by docker-php-ext
  command: docker-php-ext-install {{ item }}
  with_items: "{{ ext_install_php_packages }}"

- name: create php-fpm default folder
  file:
    path: /etc/php-fpm.d/
    state: directory
    mode: 0755
    owner: root
    group: root

- name: "Configure php.ini overrides for fpm"
  template:
    src: php-fpm.j2
    dest: /etc/php-fpm.d/architrave-fpm.conf
    owner: root
    group: root
    mode: 0644

- name: "Configure php.ini overrides for cli"
  template:
    src: php-cli.j2
    dest: /etc/php-fpm.d/architrave-cli.conf
    owner: root
    group: root
    mode: 0644

- name: "Copy index.php"
  template:
    src: index.php.j2
    dest: /var/www/html/index.php
    owner: root
    group: root
    mode: 0644

- name: "Add www config"
  template:
    src: php-www.j2
    dest: /usr/local/etc/php-fpm.d/www.conf
    owner: root
    group: root
    mode: 0644
