apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: fpm
  name: fpm
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: fpm
    spec:
      containers:
      - image: dockerchampion/fpm:arctv-v1
        name: fpm
        ports:
        - containerPort: 9000
        resources: {}
      restartPolicy: Always
status: {}
