---
- name: load iptables
  command: /etc/network/if-pre-up.d/iptables

- name: bring up iptables
  copy:
    src: iptables
    dest: /etc/network/if-pre-up.d/iptables
    mode: 0755
    owner: root
    group: root
